/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PhoneListing {
  'id' : bigint,
  'model' : string,
  'retailPrice' : bigint,
  'inStock' : boolean,
  'naiasaPrice' : bigint,
  'storage' : bigint,
  'imei' : string,
  'componentHistory' : Array<string>,
  'batteryHealth' : bigint,
  'brand' : string,
  'condition' : string,
  'diagnosticResults' : Array<string>,
}
export interface SellerSubmission {
  'id' : bigint,
  'status' : string,
  'model' : string,
  'storage' : bigint,
  'pickupSlot' : string,
  'timestamp' : bigint,
  'brand' : string,
  'quotedPrice' : bigint,
  'condition' : string,
  'diagnosticResults' : Array<string>,
}
export interface _SERVICE {
  'getAllListings' : ActorMethod<[], Array<PhoneListing>>,
  'getAllSellerSubmissions' : ActorMethod<[], Array<SellerSubmission>>,
  'getListingById' : ActorMethod<[bigint], PhoneListing>,
  'getListingsByBrand' : ActorMethod<[string], Array<PhoneListing>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitSellRequest' : ActorMethod<
    [string, string, bigint, string, Array<string>, string],
    SellerSubmission
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];