/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhoneListing = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'retailPrice' : IDL.Nat,
  'inStock' : IDL.Bool,
  'naiasaPrice' : IDL.Nat,
  'storage' : IDL.Nat,
  'imei' : IDL.Text,
  'componentHistory' : IDL.Vec(IDL.Text),
  'batteryHealth' : IDL.Nat,
  'brand' : IDL.Text,
  'condition' : IDL.Text,
  'diagnosticResults' : IDL.Vec(IDL.Text),
});
export const SellerSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'model' : IDL.Text,
  'storage' : IDL.Nat,
  'pickupSlot' : IDL.Text,
  'timestamp' : IDL.Int,
  'brand' : IDL.Text,
  'quotedPrice' : IDL.Nat,
  'condition' : IDL.Text,
  'diagnosticResults' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllListings' : IDL.Func([], [IDL.Vec(PhoneListing)], ['query']),
  'getAllSellerSubmissions' : IDL.Func(
      [],
      [IDL.Vec(SellerSubmission)],
      ['query'],
    ),
  'getListingById' : IDL.Func([IDL.Nat], [PhoneListing], ['query']),
  'getListingsByBrand' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PhoneListing)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'submitSellRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [SellerSubmission],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhoneListing = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'retailPrice' : IDL.Nat,
    'inStock' : IDL.Bool,
    'naiasaPrice' : IDL.Nat,
    'storage' : IDL.Nat,
    'imei' : IDL.Text,
    'componentHistory' : IDL.Vec(IDL.Text),
    'batteryHealth' : IDL.Nat,
    'brand' : IDL.Text,
    'condition' : IDL.Text,
    'diagnosticResults' : IDL.Vec(IDL.Text),
  });
  const SellerSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'model' : IDL.Text,
    'storage' : IDL.Nat,
    'pickupSlot' : IDL.Text,
    'timestamp' : IDL.Int,
    'brand' : IDL.Text,
    'quotedPrice' : IDL.Nat,
    'condition' : IDL.Text,
    'diagnosticResults' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllListings' : IDL.Func([], [IDL.Vec(PhoneListing)], ['query']),
    'getAllSellerSubmissions' : IDL.Func(
        [],
        [IDL.Vec(SellerSubmission)],
        ['query'],
      ),
    'getListingById' : IDL.Func([IDL.Nat], [PhoneListing], ['query']),
    'getListingsByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PhoneListing)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'submitSellRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [SellerSubmission],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };